[versions]
coroutines = "1.4.2-native-mt"
serialization = "1.0.1"
ktor = "1.5.2"
okio = "3.0.0-alpha.2"
logback = "1.2.3"
maven-publish = "0.14.2"

[libraries]
# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
# Serialization
serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
# Ktor
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-curl = { group = "io.ktor", name = "ktor-client-curl", version.ref = "ktor" }
ktor-client-apache = { group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }
# Okio
okio-multiplatform = { group = "com.squareup.okio", name = "okio-multiplatform", version.ref = "okio" }
# Logback
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
# Maven publish
maven-publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish"}
