package com.aallam.openai.api.chat

import com.aallam.openai.api.core.FinishReason
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
@Serializable
public data class ChatChoice(
    /**
     * Chat choice index.
     */
    @SerialName("index") public val index: Int,
    /**
     * The generated chat message.
     */
    @SerialName("message") public val message: ChatMessage,
    /**
     * The reason why OpenAI stopped generating.
     */
    @SerialName("finish_reason") public val finishReason: FinishReason? = null,
    /**
     * Log probability information for the choice.
     */
    @SerialName("logprobs") public val logprobs: Logprobs? = null,
)
