package com.aallam.openai.api.chat;

import com.aallam.openai.api.core.FinishReason
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
@Serializable
public data class ChatChunk(
    /**
     * Chat choice index.
     */
    @SerialName("index") public val index: Int,
    /**
     * The generated chat message.
     */
    @SerialName("delta") public val delta: ChatDelta? = null,

    /**
     * Azure content filter offsets
     */
    @SerialName("content_filter_offsets") public val contentFilterOffsets: ContentFilterOffsets? = null,

    /**
     * Azure content filter results
     */
    @SerialName("content_filter_results") public val contentFilterResults: ContentFilterResults? = null,

    /**
     * The reason why OpenAI stopped generating.
     */
    @SerialName("finish_reason") public val finishReason: FinishReason?,
)
