package com.aallam.openai.api.chat

import com.aallam.openai.api.chat.internal.ToolType
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The tool call generated by the model, such as function call.
 */
@Serializable
public data class ToolCall(
    /** The ID of the tool call. **/
    @SerialName("id") val id: String,
    /** The type of the tool. **/
    @SerialName("type") val type: ToolType,
    /** The function that the model called. **/
    @SerialName("function") val function: FunctionCall? = null
)
