package com.aallam.openai.api.responses

import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.JsonContentPolymorphicSerializer
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlin.jvm.JvmInline

@Serializable(with = CodeInterpreterContainerSerializer::class)
public sealed interface CodeInterpreterContainer


internal class CodeInterpreterContainerSerializer :
    JsonContentPolymorphicSerializer<CodeInterpreterContainer>(CodeInterpreterContainer::class) {
    override fun selectDeserializer(element: JsonElement): DeserializationStrategy<CodeInterpreterContainer> {
        return when (element) {
            is JsonPrimitive -> CodeInterpreterContainerId.serializer()
            is JsonObject -> CodeInterpreterContainerAuto.serializer()
            else -> throw SerializationException("Unsupported JSON element: $element")
        }
    }
}

@Serializable
@JvmInline
public value class CodeInterpreterContainerId(
    public val value: String
) : CodeInterpreterContainer

@Serializable
@SerialName("auto")
public data class CodeInterpreterContainerAuto(
    /**
     * An optional list of uploaded files to make available to your code.
     */
    @SerialName("file_ids") val fileIds: List<String> = emptyList()
) : CodeInterpreterContainer

/**
 * A tool call to run code.
 */
@Serializable
@SerialName("code_interpreter_call")
public data class CodeInterpreterToolCall(

    /**
     * The code to run, or null if not available.
     */
    @SerialName("code")
    val code: String? = null,

    /**
     * The ID of the container used to run the code.
     */
    @SerialName("container_id")
    val containerId: String,

    /**
     * The unique ID of the code interpreter tool call.
     */
    @SerialName("id")
    override val id: String,

    /**
     * The outputs generated by the code interpreter, such as logs or images. Can be null if no outputs are available.
     */
    @SerialName("outputs")
    val outputs: List<CodeInterpreterOutput>? = null,

    /**
     * The status of the function tool call.
     */
    @SerialName("status")
    val status: ResponseStatus

) : ResponseOutput

@Serializable
public sealed interface CodeInterpreterOutput

/**
 * The logs output from the code interpreter.
 */
@Serializable
@SerialName("logs")
public data class CodeInterpreterOutputLogs(

    /**
     * The logs output from the code interpreter.
     */
    @SerialName("logs")
    val logs: List<String>

) : CodeInterpreterOutput

/**
 * The image output from the code interpreter.
 */
@Serializable
@SerialName("image")
public data class CodeInterpreterOutputImage(
    /**
     * The URL of the image output from the code interpreter.
     */
    @SerialName("url")
    val url: String,
) : CodeInterpreterOutput
