package com.aallam.openai.api.responses

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline

/**
 * Represents the format of input for a custom tool.
 */
@Serializable
public sealed interface CustomToolFormat

/**
 * Unconstrained free-form text.
 */
@Serializable
@SerialName("text")
public object CustomToolTextFormat : CustomToolFormat

/**
 * A grammar defined by the user.
 */
@Serializable
@SerialName("grammar")
public data class CustomToolGrammarFormat(
    /** The grammar definition.*/
    @SerialName("definition")
    val definition: String,

    /** The syntax of the grammar definition. One of `lark` or `regex`. */
    @SerialName("syntax")
    val syntax: Syntax
) : CustomToolFormat {

    /**
     * Represents the syntax of a grammar definition.
     */
    @JvmInline
    @Serializable
    public value class Syntax(public val value: String) {
        public companion object {
            /** Lark syntax for defining grammars. */
            public val Lark: Syntax = Syntax("lark")

            /** Regular expression syntax for defining grammars. */
            public val Regex: Syntax = Syntax("regex")
        }
    }
}

/**
 * A call to a custom tool created by the model.
 */
@Serializable
@SerialName("custom_tool_call")
public data class CustomToolCall(

    /**
     * The unique ID of the custom tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,

    /**
     * The input for the custom tool call generated by the model.
     */
    @SerialName("input")
    val input: String,

    /**
     * The name of the custom tool being called.
     */
    @SerialName("name")
    val name: String,

    /**
     * The unique ID of the custom tool call in the OpenAI platform.
     */
    @SerialName("id")
    override val id: String

) : ResponseOutput


/**
 * The output of a custom tool call from your code, being sent back to the model.
 */
@Serializable
@SerialName("custom_tool_call_output")
public data class CustomToolCallOutput(
    /**
     * The unique ID of the custom tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,

    /**
     * The output from the custom tool call generated by your code.
     */
    @SerialName("output")
    val output: String,

    /**
     * The unique ID of the custom tool call in the OpenAI platform.
     */
    @SerialName("id")
    val id: String? = null

) : ResponseItem
