package com.aallam.openai.api.responses

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject

/**
 * Function tool call in a response
 */
@Serializable
@SerialName("function_call")
public data class FunctionToolCall(
    /**
     * The unique ID of the function tool call.
     */
    @SerialName("id")
    override val id: String,

    /**
     * The status of the function tool call.
     */
    @SerialName("status")
    val status: ResponseStatus,

    /**
     * The unique ID of the function tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,

    /**
     * The name of the function to run.
     */
    @SerialName("name")
    val name: String,

    /**
     * A JSON string of the arguments to pass to the function.
     */
    @SerialName("arguments")
    val arguments: String,
) : ResponseOutput {

    /**
     * Decodes the [arguments] JSON string into a JsonObject.
     * If [arguments] is null, the function will return null.
     *
     * @param json The Json object to be used for decoding, defaults to a default Json instance
     */
    public fun argumentsAsJson(json: Json = Json): JsonObject = json.decodeFromString(arguments)

}

/**
 * The output of a function tool call.
 *
 */
@Serializable
@SerialName("function_call_output")
public data class FunctionToolCallOutput(

    /**
     * The unique ID of the function tool call output. Populated when this item is returned via API.
     */
    @SerialName("id")
    val id: String? = null,

    /**
     * The unique ID of the function tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,

    /**
     * A JSON string of the output of the function tool call.
     */
    @SerialName("output")
    val output: String,

    /**
     * The status of the item. One of in_progress, completed, or incomplete. Populated when items are returned via API.
     */
    @SerialName("status")
    val status: ResponseStatus? = null
) : ResponseItem
