package com.aallam.openai.api.responses

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A tool call to run a command on the local shell.
 */
@Serializable
@SerialName("local_shell_call")
public data class LocalShellToolCall(

    /**
     * Execute a shell command on the server.
     */
    @SerialName("action")
    val action: LocalShellToolAction,

    /**
     * The unique ID of the local shell tool call generated by the model.
     */
    @SerialName("call_id")
    val callId: String,

    /**
     * The unique ID of the local shell call.
     */
    @SerialName("id")
    override val id: String,

    /**
     * The status of the local shell call.
     */
    @SerialName("status")
    val status: ResponseStatus

) : ResponseOutput

/**
 * The action to be performed by the local shell tool.
 */
@Serializable
@SerialName("exec")
public data class LocalShellToolAction(

    /**
     * The command to run.
     */
    @SerialName("command")
    val command: String,

    /**
     * Environment variables to set for the command.
     */
    @SerialName("env")
    val env: Map<String, String> = emptyMap(),

    /**
     * Optional timeout in milliseconds for the command.
     */
    @SerialName("timeout_ms")
    val timeoutMs: Int? = null,

    /**
     * Optional user to run the command as.
     */
    @SerialName("user")
    val user: String? = null,

    /**
     * The working directory to run the command in.
     */
    @SerialName("working_directory")
    val workingDirectory: String? = null

)

/**
 * The output of a local shell tool call.
 */
@Serializable
@SerialName("local_shell_call_output")
public data class LocalShellToolCallOutput(

    /**
     * The unique ID of the local shell tool call generated by the model.
     */
    @SerialName("id")
    val id: String,

    /**
     * A JSON string of the output of the local shell tool call.
     */
    @SerialName("output")
    val output: String,

    /**
     * The status of the local shell call.
     */
    @SerialName("status")
    val status: ResponseStatus

) : ResponseItem
