package com.aallam.openai.api.responses

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A single output item in the response
 */
@Serializable
public sealed interface ResponseOutput : ResponseItem {

    /**
     * The ID of the output item.
     * Will always be populated when coming from the API. It is optional here, so you can construct your own ResponseMessages.
     */
    @SerialName("id")
    public val id: String?
}


/**
 * A message input to the model with a role indicating instruction following hierarchy. Instructions given with the developer or system role take precedence over instructions given with the user role. Messages with the assistant role are presumed to have been generated by the model in previous interactions.
 *
 */
@Serializable
@SerialName("message")
public data class ResponseMessage(


    /**
     * The role of the author of this message.
     */
    @SerialName("role") public val role: ResponseRole,

    /**
     * A list of one or many input items to the model, containing different content types.
     *
     * Important:
     * If the role is "Assistant", only ResponseOutputText and Refusal are allowed in the content.
     * If the role is "System", only ResponseInputText is allowed in the content.
     * If the role is "User", only ResponseInputText, ResponseInputImage,
     * and ResponseInputFile are allowed in the content.
     *
     */
    @SerialName("content") public val content: List<ResponseContent> = emptyList(),
    //Implementation note: If we were to implement this distinction between input and output messages with proper polymorphism, serialization would break because of the common "message" type.

    /**
     * The unique ID of the input message.
     */
    @SerialName("id") public override val id: String? = null,

    /**
     * The status of item. One of in_progress, completed, or incomplete. Populated when items are returned via API.
     */
    @SerialName("status") public val status: ResponseStatus? = null,
) : ResponseOutput

/**
 * Represents a chat message part.
 */
@Serializable
public sealed interface ResponseContent

/**
 * Text output from the model
 */
@Serializable
@SerialName("output_text")
public data class ResponseOutputText(

    /**
     * The text output from the model.
     */
    @SerialName("text")
    val text: String,

    /**
     * The annotations of the text output.
     */
    @SerialName("annotations")
    val annotations: List<Annotation> = emptyList()
) : ResponseContent

/**
 * Refusal message from the model
 */
@Serializable
@SerialName("refusal")
public data class Refusal(

    /**
     * The refusal explanation from the model.
     */
    @SerialName("refusal")
    val refusal: String
) : ResponseContent


/**
 * An annotation in text output
 */
@Serializable
public sealed interface Annotation

/**
 * A citation to a file.
 */
@Serializable
@SerialName("file_citation")
public data class FileCitation(
    /**
     * The ID of the file.
     *
     */
    @SerialName("file_id")
    val fileId: String,

    /**
     * The index of the file in the list of files.
     */
    @SerialName("index")
    val index: Int

) : Annotation

/**
 * A citation for a web resource used to generate a model response.
 */
@Serializable
@SerialName("url_citation")
public data class UrlCitation(

    /**
     * The title of the web resource.
     */
    @SerialName("title")
    val title: String,

    /**
     * The URL of the web resource.
     */
    @SerialName("url")
    val url: String,

    /**
     * The index of the first character of the URL citation in the message.
     */
    @SerialName("start_index")
    val startIndex: Int,

    /**
     * The index of the last character of the URL citation in the message.
     */
    @SerialName("end_index")
    val endIndex: Int
) : Annotation

/**
 * A path to a file.
 */
@Serializable
@SerialName("file_path")
public data class FilePath(

    /**
     * The ID of the file.
     */
    @SerialName("file_id")
    val fileId: String,

    /**
     * The index of the file in the list of files.
     */
    @SerialName("index")
    val index: Int
) : Annotation


/**
 * Reasoning item for model reasoning
 */
@Serializable
@SerialName("reasoning")
public data class Reasoning(
    /**
     * The unique ID of the reasoning item.
     */
    @SerialName("id")
    override val id: String,

    /**
     * Reasoning summary content.
     */
    @SerialName("summary")
    val summary: List<SummaryText>,

    /**
     * Reasoning text contents.
     */
    @SerialName("content")
    val content: List<ReasoningText>? = null, // Implementation note: OpenAI doc says this is always present, but it isn't

    /**
     * The encrypted content of the reasoning item - populated when a response is generated with `reasoning.encrypted_content` in the `include` parameter.
     */
    @SerialName("encrypted_content")
    val encryptedContent: String? = null,

    /**
     * The status of the reasoning item.
     */
    @SerialName("status")
    val status: ResponseStatus? = null

) : ResponseOutput

/**
 * A summary item in the reasoning output
 */
@Serializable
@SerialName("summary_text")
public data class SummaryText(
    /**
     * A short summary of the reasoning used by the model.
     */
    @SerialName("text")
    val text: String,
) {
    @SerialName("type")
    @Required
    val type: String = "summary_text" // Implementation note: We need to specify the type explicitly because this is not a polymorphic type
}

/**
 * A summary text item in the reasoning output
 */
@Serializable
@SerialName("reasoning_text")
public data class ReasoningText(
    /**
     * Reasoning text output from the model.
     */
    @SerialName("text")
    val text: String,
) {
    @SerialName("type")
    @Required
    val type: String = "reasoning_text" // Implementation note: We need to specify the type explicitly because this is not a polymorphic type
}
