package com.aallam.openai.api.image

import com.aallam.openai.api.BetaOpenAI
import com.aallam.openai.api.OpenAIDsl
import com.aallam.openai.api.model.ModelId

/**
 * Image generation request.
 */
public class ImageCreation(
    /**
     * A text description of the desired image(s).
     * Maximum length: 32000 characters for GPT image models, 4000 for dall-e-3, 1000 for dall-e-2.
     */
    public val prompt: String,

    /**
     * The model to use for image generation.
     * One of dall-e-2, dall-e-3, or a GPT image model (gpt-image-1, gpt-image-1-mini, gpt-image-1.5).
     * Defaults to dall-e-2 unless a parameter specific to the GPT image models is used.
     */
    public val model: ModelId? = null,

    /**
     * The number of images to generate. Must be between 1 and 10.
     */
    public val n: Int? = null,
    /**
     * The size of the generated images.
     */
    public val size: ImageSize? = null,

    /**
     * The quality of the image that will be generated.
     * - auto (default): automatically select the best quality for the given model
     * - high, medium, low: supported for GPT image models
     * - hd, standard: supported for dall-e-3
     * - standard: the only option for dall-e-2
     */
    public val quality: Quality? = null,

    /**
     * The style of the generated images. Must be one of [Style.Vivid] or `[Style.Natural]`. Vivid causes the model to
     * lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less
     * hyper-real looking images. This param is only supported for dall-e-3.
     */
    public val style: Style? = null,

    /**
     * Allows setting transparency for the background of the generated image(s).
     * This parameter is only supported for the GPT image models.
     * Must be one of transparent, opaque, or auto (default value).
     */
    public val background: Background? = null,

    /**
     * Control the content-moderation level for images generated by the GPT image models.
     * Must be either low for less restrictive filtering or auto (default value).
     */
    public val moderation: Moderation? = null,

    /**
     * The format in which the generated images are returned.
     * This parameter is only supported for the GPT image models.
     * Must be one of png, jpeg, or webp.
     */
    public val outputFormat: OutputFormat? = null,

    /**
     * The compression level (0-100%) for the generated images.
     * This parameter is only supported for the GPT image models with the webp or jpeg output formats.
     * Defaults to 100.
     */
    public val outputCompression: Int? = null,

    /**
     * The number of partial images to generate.
     * This parameter is used for streaming responses that return partial images.
     * Value must be between 0 and 3. When set to 0, the response will be a single image sent in one streaming event.
     */
    public val partialImages: Int? = null,

    /**
     * The format in which generated images with dall-e-2 and dall-e-3 are returned.
     * Must be one of url or b64_json. URLs are only valid for 60 minutes after the image has been generated.
     * This parameter isn't supported for the GPT image models, which always return base64-encoded images.
     */
    public val responseFormat: String? = null,

    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
     */
    public val user: String? = null,
)

/**
 * Image generation request.
 */
@BetaOpenAI
public fun imageCreation(block: ImageCreationBuilder.() -> Unit): ImageCreation =
    ImageCreationBuilder().apply(block).build()

/**
 * Builder of [ImageCreation] instances.
 */
@BetaOpenAI
@OpenAIDsl
public class ImageCreationBuilder {

    /**
     * A text description of the desired image(s).
     * Maximum length: 32000 characters for GPT image models, 4000 for dall-e-3, 1000 for dall-e-2.
     */
    public var prompt: String? = null

    /**
     * The model to use for image generation.
     * One of dall-e-2, dall-e-3, or a GPT image model (gpt-image-1, gpt-image-1-mini, gpt-image-1.5).
     */
    public var model: ModelId? = null

    /**
     * The number of images to generate. Must be between 1 and 10.
     */
    public var n: Int? = null

    /**
     * The size of the generated images.
     */
    public var size: ImageSize? = null

    /**
     * The quality of the image that will be generated.
     */
    public var quality: Quality? = null

    /**
     * The style of the generated images. Must be one of vivid or natural.
     * This param is only supported for dall-e-3.
     */
    public var style: Style? = null

    /**
     * Allows to set transparency for the background of the generated image(s).
     * This parameter is only supported for the GPT image models.
     */
    public var background: Background? = null

    /**
     * Control the content-moderation level for images generated by the GPT image models.
     */
    public var moderation: Moderation? = null

    /**
     * The format in which the generated images are returned.
     * This parameter is only supported for the GPT image models.
     */
    public var outputFormat: OutputFormat? = null

    /**
     * The compression level (0-100%) for the generated images.
     * This parameter is only supported for the GPT image models with the webp or jpeg output formats.
     */
    public var outputCompression: Int? = null

    /**
     * The number of partial images to generate (0-3).
     * This parameter is used for streaming responses that return partial images.
     */
    public var partialImages: Int? = null

    /**
     * The format in which generated images with dall-e-2 and dall-e-3 are returned.
     * Must be one of url or b64_json.
     */
    public var responseFormat: String? = null

    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
     */
    public var user: String? = null

    /**
     * Creates the [ImageCreation] instance
     */
    public fun build(): ImageCreation = ImageCreation(
        prompt = requireNotNull(prompt),
        model = model,
        n = n,
        size = size,
        quality = quality,
        style = style,
        background = background,
        moderation = moderation,
        outputFormat = outputFormat,
        outputCompression = outputCompression,
        partialImages = partialImages,
        responseFormat = responseFormat,
        user = user,
    )
}
