package com.aallam.openai.api.image
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline
/**
 * Control the content-moderation level for images generated by the GPT image models.
 */
@Serializable
@JvmInline
public value class Moderation(public val value: String) {
    public companion object {
        /**
         * Automatic content-moderation level (default).
         */
        public val Auto: Moderation = Moderation("auto")
        /**
         * Less restrictive filtering.
         */
        public val Low: Moderation = Moderation("low")
    }
}
